---

version: '3'

services:

  redis:
    image: redis
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start"
    ports:
      - "3000:3000"
    volumes:
      - .:/root/code/chat-app
    depends_on:
      - solargraph

  # https://github.com/neoclide/coc-solargraph#configuration-options
  # external server
  solargraph:
    build: .
    command: "bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    ports:
      - "7658:7658"
    volumes:
      - .:/root/code/chat-app

  spring:
    build: .
    command: bin/spring server
    pid: host
    volumes:
      - .:/root/code/chat-app
      - /tmp:/tmp

volumes:
  redis:
  # caddy_config:
  # caddy_data:
